Update position of date range slider under charts
healthmap/mriids2 pull request #161
Opened 2021-03-26 15:35 UTC by shaileshmahajan

Fixes: https://github.com/healthmap/mriids2/issues/151

Test Case - 
- Pull down the code.
- Run locally or use
- Make sure the slider looks ok when switching between outbreaks as well as changing timespan

2021-03-29 13:23 UTC, rachelchorney requested changes
I think the entire chart and slider should be centered. Here's what I am seeing:
![image](https://user-images.githubusercontent.com/4304814/112843121-40a19400-9070-11eb-9fc4-107b182d0c0a.png)

I think it should look more like this:
![image](https://user-images.githubusercontent.com/4304814/112843212-5a42db80-9070-11eb-996c-f9e142801676.png)

2021-03-31 13:53 UTC, rachelchorney commented
@shaileshmahajan I ended up centering the chart, legend and slider:
![image](https://user-images.githubusercontent.com/4304814/113155421-ff8fb800-9206-11eb-8937-bb5e15048fe2.png)

2021-03-31 16:03 UTC, fernandodonaire approved these changes
Looks good to me @rachelchorney ! We are also no longer seeing the issue with the date range not being updated when you switch between outbreaks.

<img width="1614" alt="Screen Shot 2021-03-31 at 12 02 41 PM" src="https://user-images.githubusercontent.com/40768918/113175045-032c3a80-9219-11eb-9078-c1bc5b77a3f6.png">

2021-03-31 18:09 UTC, rachelchorney approved these changes

2021-03-31 18:23 UTC, merged