MRIID-5 Added covid data to chart
healthmap/mriids2 pull request #47
Opened 2020-12-04 19:15 UTC by fernandodonaire

![Screen Shot 2020-12-04 at 2 14 15 PM](https://user-images.githubusercontent.com/40768918/101204932-003e8600-363b-11eb-92d6-c7b7256d7cde.png)

Can be tested by:

1) Pulling down this branch.
2) Running the app locally.
3) Selecting COVID 19 in the Sidebar. You should see the COVID case count data in the chart.

2020-12-04 19:44 UTC, SpencerMarks-IDHA commented on src/utils/__tests__/chartDataHelpers.test.js
> +        null,
we should avoid designing APIs that accept null as valid. etc.

2020-12-04 19:45 UTC, SpencerMarks-IDHA commented on src/utils/__tests__/chartDataHelpers.test.js
> +        null,
or maybe this is a negative test case?

2020-12-04 19:45 UTC, SpencerMarks-IDHA commented on src/utils/__tests__/chartDataHelpers.test.js
> +      )
in any case, great to see test cases.

2020-12-04 19:47 UTC, SpencerMarks-IDHA requested changes
One change request,  but only if feasible.

2020-12-04 19:47 UTC, SpencerMarks-IDHA commented on src/utils/chartDataHelpers.js
> +        chartData.push([new Date(dateKey), covidDataCombined.cases[dateKey]]);
the complexity here makes the code hard to follow. The comments are great boon, but I wonder if you could break this up into methods or otherwise refactored?

2020-12-04 20:06 UTC, fernandodonaire commented on src/utils/chartDataHelpers.js
> +        chartData.push([new Date(dateKey), covidDataCombined.cases[dateKey]]);
Yeah good call. I can break up the `prepareCovidDataForCharts()` function into 2 separate functions. One to get 'all countries' data and another to get the country specific data.

2020-12-07 14:07 UTC, fernandodonaire commented on src/utils/chartDataHelpers.js
> +        chartData.push([new Date(dateKey), covidDataCombined.cases[dateKey]]);
Hey @SpencerMarks-IDHA , I refactored the `prepareCovidDataForCharts()` function. Can you please review this again?

2020-12-11 14:31 UTC, SpencerMarks-IDHA approved these changes

2020-12-11 14:34 UTC, merged